FROM mcr.microsoft.com/devcontainers/python:3.12

# Install any additional dependencies here
# RUN apt-get update && apt-get install -y <package-name>

# Switch back to dialog for any ad-hoc use of apt-get
ENV DEBIAN_FRONTEND=dialog
